exporter_port: 9158 # Port on which prometheus can call this exporter to get metrics
namespace: nexus
host: <host_header> # Override Host Header if wanted
log_level: debug|info|warn|error
json_data_url: <url_with_scheme> # Url to get json data used for fetching metric values, and with the /service/metrics/data
basic_auth_user: <username> # User to connect to Nexus. Optional, leave empty for empty Basic auth
basic_auth_password: <password>
metric_name_prefix: nexus # All metric names will be prefixed with this value
metrics: # Default JSON metrics from /service/metrics/data
- type: gauge
  path: $.gauges
- type: meters
  path: $.meters
